import { Drama } from "./types";

// Extended mock data with more variety and genres
export const mockDramas: Drama[] = [
    {
        id: "1",
        title: "Vincenzo",
        endpoint: "vincenzo",
        thumbnail: "/posters/vincenzo.png",
        rating: "9.2",
        year: "2021",
        genres: ["Crime", "Comedy", "Romance"],
        status: "completed",
        description: "An Italian lawyer returns to Korea to recover hidden gold.",
    },
    {
        id: "2",
        title: "Crash Landing on You",
        endpoint: "crash-landing-on-you",
        thumbnail: "/posters/crash-landing.png",
        rating: "9.4",
        year: "2020",
        genres: ["Romance", "Comedy", "Drama"],
        status: "completed",
        description: "A South Korean heiress crash-lands in North Korea.",
    },
    {
        id: "3",
        title: "Squid Game",
        endpoint: "squid-game",
        thumbnail: "/posters/squid-game.png",
        rating: "8.8",
        year: "2021",
        genres: ["Thriller", "Drama", "Action"],
        status: "completed",
        description: "Contestants compete in children's games for a deadly prize.",
    },
    {
        id: "4",
        title: "All of Us Are Dead",
        endpoint: "all-of-us-are-dead",
        thumbnail: "/posters/all-of-us-are-dead.png",
        rating: "8.5",
        year: "2022",
        genres: ["Horror", "Action", "Thriller"],
        status: "completed",
        description: "High school becomes ground zero for a zombie outbreak.",
    },
    {
        id: "5",
        title: "Business Proposal",
        endpoint: "business-proposal",
        thumbnail: "/posters/business-proposal.png",
        rating: "8.7",
        year: "2022",
        genres: ["Romance", "Comedy"],
        status: "completed",
        description: "An employee's blind date turns out to be her CEO.",
    },
    {
        id: "6",
        title: "Hometown Cha-Cha-Cha",
        endpoint: "hometown-cha-cha-cha",
        thumbnail: "/posters/hometown-cha-cha-cha.png",
        rating: "8.9",
        year: "2021",
        genres: ["Romance", "Comedy", "Drama"],
        status: "completed",
        description: "A dentist moves to a seaside village and finds love.",
    },
    {
        id: "7",
        title: "Goblin",
        endpoint: "goblin",
        thumbnail: "/placeholder-movie.png",
        rating: "9.3",
        year: "2016",
        genres: ["Romance", "Drama", "Fantasy"],
        status: "completed",
        description: "An immortal goblin searches for his bride to end his life.",
    },
    {
        id: "8",
        title: "Itaewon Class",
        endpoint: "itaewon-class",
        thumbnail: "/placeholder-movie.png",
        rating: "8.6",
        year: "2020",
        genres: ["Drama", "Romance"],
        status: "completed",
        description: "An ex-convict opens a bar to get revenge on a food conglomerate.",
    },
    {
        id: "9",
        title: "Kingdom",
        endpoint: "kingdom",
        thumbnail: "/placeholder-movie.png",
        rating: "8.7",
        year: "2019",
        genres: ["Horror", "Thriller", "Action"],
        status: "completed",
        description: "A crown prince investigates a mysterious plague.",
    },
    {
        id: "10",
        title: "Descendants of the Sun",
        endpoint: "descendants-of-the-sun",
        thumbnail: "/placeholder-movie.png",
        rating: "9.0",
        year: "2016",
        genres: ["Romance", "Action", "Drama"],
        status: "completed",
        description: "A soldier and a doctor fall in love in a war-torn country.",
    },
    {
        id: "11",
        title: "My Love from the Star",
        endpoint: "my-love-from-the-star",
        thumbnail: "/placeholder-movie.png",
        rating: "8.9",
        year: "2013",
        genres: ["Romance", "Comedy", "Fantasy"],
        status: "completed",
        description: "An alien falls in love with a famous actress.",
    },
    {
        id: "12",
        title: "Signal",
        endpoint: "signal",
        thumbnail: "/placeholder-movie.png",
        rating: "9.1",
        year: "2016",
        genres: ["Crime", "Thriller", "Drama"],
        status: "completed",
        description: "Detectives from different eras communicate through a walkie-talkie.",
    },
];
