import { Drama } from "./types";

// Extended mock data with more variety, countries, and explicit status
export const mockDramas: Drama[] = [
    {
        id: "1",
        title: "Vincenzo",
        endpoint: "vincenzo",
        thumbnail: "/posters/vincenzo.png",
        rating: "9.2",
        year: "2021",
        genres: ["Crime", "Comedy", "Romance"],
        status: "completed",
        country: "South Korea",
        description: "An Italian lawyer returns to Korea to recover hidden gold.",
    },
    {
        id: "2",
        title: "Crash Landing on You",
        endpoint: "crash-landing-on-you",
        thumbnail: "/posters/crash-landing.png",
        rating: "9.4",
        year: "2020",
        genres: ["Romance", "Comedy", "Drama"],
        status: "completed",
        country: "South Korea",
        description: "A South Korean heiress crash-lands in North Korea.",
    },
    {
        id: "3",
        title: "Squid Game",
        endpoint: "squid-game",
        thumbnail: "/posters/squid-game.png",
        rating: "8.8",
        year: "2021",
        genres: ["Thriller", "Drama", "Action"],
        status: "completed",
        country: "South Korea",
        description: "Contestants compete in children's games for a deadly prize.",
    },
    {
        id: "4",
        title: "All of Us Are Dead",
        endpoint: "all-of-us-are-dead",
        thumbnail: "/posters/all-of-us-are-dead.png",
        rating: "8.5",
        year: "2022",
        genres: ["Horror", "Action", "Thriller"],
        status: "completed",
        country: "South Korea",
        description: "High school becomes ground zero for a zombie outbreak.",
    },
    {
        id: "5",
        title: "Business Proposal",
        endpoint: "business-proposal",
        thumbnail: "/posters/business-proposal.png",
        rating: "8.7",
        year: "2022",
        genres: ["Romance", "Comedy"],
        status: "completed",
        country: "South Korea",
        description: "An employee's blind date turns out to be her CEO.",
    },
    {
        id: "6",
        title: "Hometown Cha-Cha-Cha",
        endpoint: "hometown-cha-cha-cha",
        thumbnail: "/posters/hometown-cha-cha-cha.png",
        rating: "8.9",
        year: "2021",
        genres: ["Romance", "Comedy", "Drama"],
        status: "completed",
        country: "South Korea",
        description: "A dentist moves to a seaside village and finds love.",
    },
    {
        id: "7",
        title: "The Untamed",
        endpoint: "the-untamed",
        thumbnail: "/placeholder-movie.png",
        rating: "9.3",
        year: "2019",
        genres: ["Fantasy", "Action", "Mystery"],
        status: "completed",
        country: "China",
        description: "Two soulmates face treacherous schemes and uncover a dark mystery.",
    },
    {
        id: "8",
        title: "Alice in Borderland",
        endpoint: "alice-in-borderland",
        thumbnail: "/placeholder-movie.png",
        rating: "8.6",
        year: "2020",
        genres: ["Action", "Thriller", "Sci-Fi"],
        status: "ongoing",
        country: "Japan",
        description: "Gamers must survive deadly games in a parallel Tokyo.",
    },
    {
        id: "9",
        title: "Hidden Love",
        endpoint: "hidden-love",
        thumbnail: "/placeholder-movie.png",
        rating: "9.1",
        year: "2023",
        genres: ["Romance", "Youth", "Comedy"],
        status: "completed",
        country: "China",
        description: "A young girl crushes on her older brother's friend.",
    },
    {
        id: "10",
        title: "Moving",
        endpoint: "moving",
        thumbnail: "/placeholder-movie.png",
        rating: "9.0",
        year: "2023",
        genres: ["Action", "Supernatural", "Thriller"],
        status: "ongoing",
        country: "South Korea",
        description: "Teens with superpowers fight against dark forces with their parents.",
    },
    {
        id: "11",
        title: "My Love from the Star",
        endpoint: "my-love-from-the-star",
        thumbnail: "/placeholder-movie.png",
        rating: "8.9",
        year: "2013",
        genres: ["Romance", "Comedy", "Fantasy"],
        status: "completed",
        country: "South Korea",
        description: "An alien falls in love with a famous actress.",
    },
    {
        id: "12",
        title: "F4 Thailand",
        endpoint: "f4-thailand",
        thumbnail: "/placeholder-movie.png",
        rating: "8.5",
        year: "2021",
        genres: ["Romance", "Drama", "Youth"],
        status: "completed",
        country: "Thailand",
        description: "A poor girl attending a prestigious school stands up to rich bullies.",
    },
];
